services:
  team-work-management:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/teamwork
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Heliossn1202
    networks:
      - spring-boot-mysql-network

  mysqldb:
    image: mysql:8.0.33
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=teamwork
      - MYSQL_ROOT_PASSWORD=Heliossn1202
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-boot-mysql-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost || exit 1" ]
      retries: 10
      interval: 3s
      timeout: 30s

volumes:
  mysql-data:
networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network